### ISSUE TITLE
Things are blowing up when trying to run `git secure-tag`

### ISSUE THREAD

**Issue by MylesBorins** [indutny/git-secure-tag#3]
```

[master][v10.13.0-proposal]$ git secure-tag v10.13.0 dc2708a8a1 -sm "2018-10-30 ode.js v10.13.0 'Dubnium' (LTS) Release"
internal/child_process.js:328
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:328:11)
    at exports.spawn (child_process.js:370:9)
    at new Batch (/Users/thealphanerd/.nvm/versions/node/v6.14.4/lib/node_modules/git-secure-tag/lib/git-secure-tag/batch.js:11:15)
    at Hash.calculate (/Users/thealphanerd/.nvm/versions/node/v6.14.4/lib/node_modules/git-secure-tag/lib/git-secure-tag/hash.js:144:17)
    at async.waterfall (/Users/thealphanerd/.nvm/versions/node/v6.14.4/lib/node_modules/git-secure-tag/lib/git-secure-tag/api.js:130:12)
    at nextTask (/Users/thealphanerd/.nvm/versions/node/v6.14.4/lib/node_modules/git-secure-tag/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/Users/thealphanerd/.nvm/versions/node/v6.14.4/lib/node_modules/git-secure-tag/node_modules/async/dist/async.js:5334:5)
    at API.sign (/Users/thealphanerd/.nvm/versions/node/v6.14.4/lib/node_modules/git-secure-tag/lib/git-secure-tag/api.js:127:9)
    at Object.<anonymous> (/Users/thealphanerd/.nvm/versions/node/v6.14.4/lib/node_modules/git-secure-tag/bin/git-secure-tag:41:7)
```

**Comment by MylesBorins** [comment]
Different error with 10.x

```
/Users/thealphanerd/.nvm/versions/node/v10.12.0/lib/node_modules/git-secure-tag/lib/git-secure-tag/batch.js:17
  this.proc.stdout.on('data', data => this.onData(data));
                   ^

TypeError: Cannot read property 'on' of undefined
    at new Batch (/Users/thealphanerd/.nvm/versions/node/v10.12.0/lib/node_modules/git-secure-tag/lib/git-secure-tag/batch.js:17:20)
    at Hash.calculate (/Users/thealphanerd/.nvm/versions/node/v10.12.0/lib/node_modules/git-secure-tag/lib/git-secure-tag/hash.js:144:17)
    at async.waterfall (/Users/thealphanerd/.nvm/versions/node/v10.12.0/lib/node_modules/git-secure-tag/lib/git-secure-tag/api.js:130:12)
    at nextTask (/Users/thealphanerd/.nvm/versions/node/v10.12.0/lib/node_modules/git-secure-tag/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/Users/thealphanerd/.nvm/versions/node/v10.12.0/lib/node_modules/git-secure-tag/node_modules/async/dist/async.js:5334:5)
    at API.sign (/Users/thealphanerd/.nvm/versions/node/v10.12.0/lib/node_modules/git-secure-tag/lib/git-secure-tag/api.js:127:9)
    at Object.<anonymous> (/Users/thealphanerd/.nvm/versions/node/v10.12.0/lib/node_modules/git-secure-tag/bin/git-secure-tag:41:7)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
```
